# ======================================================================
# Справочники для select-полей формы "Добавление ТТ".
# Это перенесённые 1-в-1 значения из твоего Mini App (dropdownData).
# Если нужно поменять список — редактируй прямо здесь.
# ======================================================================

REGIONS = ["FV", "SOUTH-WEST", "TASHKENT", "TASH-OBL"]

# Область, округ и район — три независимых списка, взятых из файла
# "Лист_Microsoft_Excel.xlsx" (столбцы «Область», «Округ», «Район»).
# Зависимости между ними нет: в классификации компании, например, NAMANGAN —
# это городские районы, а NAMANGAN VILOYATI — областные, поэтому список
# округов и районов один и тот же для любой области.
OBLAST = [
    "ANDIJON VILOYATI", "BUXORO VILOYATI", "FARGONA VILOYATI", "JIZZAX VILOYATI",
    "KOKAND VILOYATI", "NAMANGAN VILOYATI", "NAVOIY VILOYATI", "QASHQADARYO VILOYATI",
    "QORAQALPOQISTON", "SAMARQAND VILOYATI", "SIRDARYO VILOYATI", "SURXANDARYO VILOYATI",
    "TOSHKENT VILOYATI", "XORAZM VILOYATI", "NAMANGAN", "CHORTOQ", "CHUST", "KOSONSOY",
    "MINGBULOQ", "NORIN", "POP", "TORAQORGON", "UCHQORGON", "UYCHI", "YANGIQORGON", "FARGONA",
    "OLTIARIQ", "QOSHTEPA", "QUVA", "SOX", "TOSHLOQ", "YOZYOVON", "ANDIJON", "ASAKA",
    "BALIQCHI", "BOSTON", "BULOQBOSHI", "IZBOSKAN", "JALAQUDUQ", "XOJAOBOD", "QORGONTEPA",
    "MARHAMAT", "OLTINKOL", "PAXTAOBOD", "SHAHRIXON", "ULUGNOR", "QOQAND", "BAGDOD",
    "BESHARIQ", "BUVAYDA", "DANGARA", "FURQAT", "RISHTON", "UCHKOPRIK", "OZBEKISTON"
]

OKRUG = [
    "AMUDARYO", "ANGOR", "ARNASOY", "BANDIXON", "BAXMAL", "BEKOBOD", "BERUNIY", "BOGOT",
    "BOKA", "BOSTONLIQ", "BOYOVUT", "BOYSUN", "BOZATOV", "BULUNGUR", "BUXORO", "CHIMBOY",
    "CHINOZ", "CHIRCHIQ", "CHIROQCHI", "DEHQONOBOD", "DENOV", "DOSTLIK", "ELLIKQALA", "FORISH",
    "GALLAOROL", "GIJDUVON", "GULISTON", "GURLAN", "GUZOR", "HAZORASP", "ISHTIXON",
    "JARQORGON", "JIZZAKH", "JOMBOY", "JONDOR", "KARMANA", "KASBI", "KATTAQORGON", "KEGEYLI",
    "KITOB", "KOGON", "KOKDALA", "KONIMEX", "KOSON", "MIRISHKOR", "MIRZACHOL", "MIRZAOBOD",
    "MOYNOQ", "MUBORAK", "MUZRABOT", "NARPAY", "NAVBAHOR", "NAVOIY", "NISHON", "NUKUS",
    "NUROBOD", "NUROTA", "OHANGARON", "OLOT", "OLTINSOY", "OQDARYO", "OQOLTIN", "OQQORGON",
    "PARKENT", "PASTDARGOM", "PAXTACHI", "PAXTAKOR", "PAYARIQ", "PESHKU", "PISKENT", "QAMASHI",
    "QANLIKOL", "QARSHI", "QIBRAY", "QIZILTEPA", "QIZIRIQ", "QONGIROT", "QORAKOL", "QORAOZAK",
    "QOROVULBOZOR", "QOSHKOPIR", "QOSHRABOT", "QUMQORGON", "ROMITAN", "SAMARQAND", "SARDOBA",
    "SARIOSIYO", "SAYXUNOBOD", "SHAHRISABZ", "SHAROF RASHIDOV", "SHEROBOD", "SHOFIRKON",
    "SHORCHI", "SHOVOT", "SHUMANAY", "SIRDARYO", "TAXIATOSH", "TAXTAKOPIR", "TERMIZ", "TOMDI",
    "TORTKOL", "TOYLOQ", "TUPROQQALA", "UCHQUDUQ", "URGANCH", "URGUT", "UZUN", "VOBKENT",
    "XATIRCHI", "XIVA", "XOJAYLI", "XONQA", "XOVOS", "YAKKABOG", "YANGIARIQ", "YANGIBOZOR",
    "YANGIOBOD", "YANGIYOL", "ZAFAROBOD", "ZANGIOTA", "ZARAFSHAN", "ZARBDOR", "ZOMIN",
    "TASHKENT"
]

RAYON = [
    "AMUDARYO TUMANI", "ANDIJON SHAHAR", "ANGOR TUMANI", "ANGREN SHAHAR", "ASAKA TUMANI",
    "ASKIYA BOZOR", "BALIQCHI TUMANI", "BAXMAL TUMANI", "BEKOBOD TUMANI", "BEKTEMIR TUMANI",
    "BERUNIY TUMANI", "BESHARIQ TUMANI", "BESHKENT SHAHAR", "BOGDOD TUMANI", "BOGOT TUMANI",
    "BOKA TUMANI", "BOSTONLIQ TUMANI", "BOZ TUMANI", "BULOQBOSHI TUMANI", "BULUNGUR TUMANI",
    "BUSTON TUMANI", "BUVAYDA TUMANI", "BUXORO SHAHAR", "CHELAK TUMANI", "CHILONZOR TUMANI",
    "CHIMBOY TUMANI", "CHINOBOD TUMANI", "CHINOZ TUMANI", "CHIRCHIQ SHAHAR",
    "CHIROQCHI TUMANI", "CHORTOQ TUMANI", "CHUST TUMANI", "DANGARA TUMANI",
    "DASHTAOBOD TUMANI", "DEHQONOBOD TUMANI", "DENOV TUMANI", "DUSTLIK TUMANI", "ECO BOZOR",
    "ELLIKQALA TUMANI", "ELOBOD SHAHAR", "FARGONA BOZOR", "FARGONA SHAHAR", "FOOD CITY BOZOR",
    "FURQAT TUMANI", "GALASIYO TUMANI", "GALLAOROL TUMANI", "GAZALKENT TUMANI",
    "GIJDUVON SHAHAR", "GOZAL TUMANI", "GULISTON SHAHAR", "GURLAN TUMANI", "GUZOR TUMANI",
    "GVARDEYSKIY BOZOR", "HAMZA SHAHAR", "HAZORASP TUMANI", "IPPODROM BOZOR",
    "ISHTIXON TUMANI", "IZBOSKAN TUMANI", "JALAQUDUQ TUMANI", "JARQORGON TUMANI",
    "JILONGU TUMANI", "JIZZAX SHAHAR", "JOMBOY TUMANI", "JONDOR TUMANI", "JUMA TUMANI",
    "KADISHEVA BOZOR", "KARMANA TUMANI", "KASBI TUMANI", "KATTAQORGON TUMANI", "KELES SHAHAR",
    "KITOB TUMANI", "KOGON TUMANI", "KONIGIL TUMANI", "KONIMEX TUMANI", "KORAKUL TUMANI",
    "KOSHKOPIR TUMANI", "KOSON TUMANI", "KOSONSOY TUMANI", "KUSHKUPIR TUMANI",
    "KUYGANYOR TUMANI", "LOYISH TUMANI", "MARGILON TUMANI", "MARHAMAT TUMANI", "MIROBOD BOZOR",
    "MIROBOD TUMANI", "MIRZO ULUGBEK TUMANI", "MUBORAK TUMANI", "MUZRABOD TUMANI",
    "NAMANGAN SHAHAR", "NARPAY TUMANI", "NAVBAHOR TUMANI", "NAVOIY SHAHAR", "NISHON TUMANI",
    "NORIN TUMANI", "NUKUS SHAHAR", "NURAFSHON TUMANI", "NUROBOD TUMANI", "NUROTA TUMANI",
    "OLMALIQ SHAHAR", "OLMAZOR TUMANI", "OLOT TUMANI", "OLOY BOZOR", "OLTIARIQ TUMANI",
    "OLTINKOL TUMANI", "OQDARYO TUMANI", "OQQORGON TUMANI", "OROMGOH TUMANI",
    "ORTACHIRCHIQ TUMANI", "ORTASAROY TUMANI", "OXANGARON TUMANI", "OZBEKISTON TUMANI",
    "PARKENT TUMANI", "PASTARGOM TUMANI", "PAXTACHI TUMANI", "PAXTAKOR TUMANI",
    "PAXTAOBOD TUMANI", "PAYARIQ TUMANI", "PAYTUG TUMANI", "PESHKU TUMANI", "PISKENT TUMANI",
    "PITNAK TUMANI", "POP TUMANI", "POYARIQ TUMANI", "QAMASHI TUMANI", "QARSHI SHAHAR",
    "QASHQADARYO", "QATORTOL BOZOR", "QIBRAY TUMANI", "QIZILTEPA TUMANI", "QIZIRIQ TUMANI",
    "QONGIROT TUMANI", "QOQON SHAHAR", "QORAKOL TUMANI", "QORASUV TUMANI", "QORGONTEPA TUMANI",
    "QOROVULBOZOR TUMANI", "QOSHKUPIR TUMANI", "QOYLIQ BOZOR", "QUMQORGON TUMANI",
    "QURGONTEPA TUMANI", "QUVA SHAHAR", "QUVASOY TUMANI", "QUYICHIRCHIQ TUMANI",
    "RISHTON TUMANI", "ROMITAN TUMANI", "SAMARQAND SHAHAR", "SAMPI BOZOR", "SARIOSIYO TUMANI",
    "SERGELI TUMANI", "SHAHRIHON TUMANI", "SHAHRISABZ SHAHAR", "SHAROF RASHIDOV TUMANI",
    "SHAYXONTOXUR TUMANI", "SHEROBOD TUMANI", "SHIMBAU TUMANI", "SHOFIRKON SHAHAR",
    "SHOFIRKON TUMANI", "SHOMANAY TUMANI", "SHOVOT TUMANI", "SHURCHI TUMANI",
    "SIRDARYO TUMANI", "TAXIATOSH TUMANI", "TAXTA KOPRIK", "TAYLOQ TUMANI", "TERMEZ SHAHAR",
    "TORAQORGON TUMANI", "TORTKOL TUMANI", "TOSHBULOQ SHAHAR", "TOSHKENT SHAHAR",
    "TOSHKENT TUMANI", "TOSHLOQ TUMANI", "TOYLOQ TUMANI", "TUPROQQALA TUMANI",
    "TURAQURGON TUMANI", "UCHKOPRIK TUMANI", "UCHQORGON TUMANI", "UCHQUDUQ TUMANI",
    "UCHTEPA TUMANI", "ULUGNOR TUMANI", "UNIVERSAM BOZOR", "URGANCH SHAHAR", "URGUT TUMANI",
    "URIKZOR BOZOR", "URTACHIRCHIQ TUMANI", "UYCHI TUMANI", "VOBKENT TUMANI", "VODIY BOZOR",
    "XAMZA SHAHAR", "XATIRCHI TUMANI", "XIVA SHAHAR", "XOJAOBOD TUMANI", "XOJAYLI TUMANI",
    "XONOBOT TUMANI", "XONQA TUMANI", "XUDJAOBOD TUMANI", "YAKKABOG TUMANI",
    "YAKKASAROY TUMANI", "YANGI BOZOR", "YANGIARIQ TUMANI", "YANGIBOZOR TUMANI",
    "YANGIHAYOT TUMANI", "YANGIQURGON TUMANI", "YANGIYOL SHAHAR", "YASHNOBOD TUMANI",
    "YAYPAN TUMANI", "YOZYOVON TUMANI", "YUNUSOBOD TUMANI", "YUQORICHIRCHIQ TUMANI",
    "ZAFAROBOD TUMANI", "ZANGIOTA TUMANI", "ZARAFSHON SHAHAR", "ZARKENT TUMANI",
    "ZOMIN TUMANI"
]

FORMAT = ["Chain", "Drogery", "Hotels", "OP.Markets", "Others", "Perfumery", "Pharmacy",
          "Super M.", "Superettes", "Web Sales"]

CHANNEL = ["B.SALOONS", "HORECA", "MOD.TRADE", "TRAD TRADE", "WHOLESALE"]

TYPE = ["FOOD", "FOOD-HPC", "HPC"]

CATEGORY = ["A", "B", "C", "D"]

DELIVERY_CODE = {
    "TASHKENT": ["D2-TOP1", "D3-TOP2", "D4-YNSBD-1", "D5-SHAYXTR", "D6-OLMAZR", "D7-CLNZR1",
                 "D8-YNSBD-2", "D9-M.ULU1", "D10-UCHTEP", "D11-MIR.YK", "D12-CLNZR2",
                 "D13-YASHNB", "D14-SRGILI", "D15-M.ULU2", "D16-CHRQ", "D17-CHRQ-1",
                 "D18-CHRQ-2", "D19-OSDO-1", "D20-OSDO-2", "D21-OSDO-3", "D22-YANG-1",
                 "D23-YANG-2", "D24-BEKBOD", "D25-ANG.OX", "D26-OLMALQ", "K1-KA", "K3-KA", "K5-KA"],
    "TOSHKENT VILOYATI": ["D2-TOP1", "D3-TOP2", "D4-YNSBD-1", "D5-SHAYXTR", "D6-OLMAZR",
                           "D7-CLNZR1", "D8-YNSBD-2", "D9-M.ULU1", "D10-UCHTEP", "D11-MIR.YK",
                           "D12-CLNZR2", "D13-YASHNB", "D14-SRGILI", "D15-M.ULU2", "D16-CHRQ",
                           "D17-CHRQ-1", "D18-CHRQ-2", "D19-OSDO-1", "D20-OSDO-2", "D21-OSDO-3",
                           "D22-YANG-1", "D23-YANG-2", "D24-BEKBOD", "D25-ANG.OX", "D26-OLMALQ",
                           "K1-KA", "K3-KA", "K5-KA"],
    "SAMARQAND VILOYATI": ["SAM-D1", "SAM-D3", "SAM-D4", "SAM-D5", "SAM-D6", "SAM-D8", "SAM-D7"],
    "BUXORO VILOYATI": ["BUX-D3", "BUX-D6", "BUX-D4", "BUX-D2", "BUX-D5", "BUX-D7", "BUX-D1"],
    "NAVOIY VILOYATI": ["NAV-D2", "NAV-D1", "NAV-D3", "NAV-D4"],
    "JIZZAX VILOYATI": ["JIZ-D2", "JIZ-D3", "JIZ-D1"],
    "SURXANDARYO VILOYATI": ["TER-D1", "TER-DJ", "TER-D2"],
    "QASHQADARYO VILOYATI": ["QAR-D3", "QAR-D1", "QAR-D2", "QAR-D4", "SHAH-D2", "SHAH-D1"],
    "XORAZM VILOYATI": ["XOR-D4", "XOR-D2", "XOR-D5", "XOR-D3", "XOR-D1", "XOR-D6"],
    "QORAQALPOQISTON": ["NUK-D3", "NUK-D2", "NUK-D1"],
    "FARGONA VILOYATI": ["FAR-D1", "FAR-D2", "FAR-D3", "FAR-D4", "FAR-D5", "QOQ-D1", "QOQ-D2",
                          "QOQ-D3", "QOQ-D4", "QOQ-D5"],
    "ANDIJON VILOYATI": ["AND-D1", "AND-D2", "AND-D3", "AND-D4", "AND-D5"],
    "NAMANGAN VILOYATI": ["NAM-D1", "NAM-D2", "NAM-D3", "NAM-D4", "NAM-D5"],
    "DEFAULT": ["DLV-101", "DLV-102", "DLV-103"],
}

DAYS = ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница"]


def get_delivery_codes(oblast: str, okrug: str = "") -> list[str]:
    """
    Коды доставщика исторически привязаны к области. Но в новом справочнике
    Ташкент указывается как ОКРУГ (в столбце «Область» его нет), поэтому
    сначала ищем по области, затем по округу, и только потом отдаём общий
    список — иначе 28 ташкентских кодов оказались бы недоступны.
    """
    if oblast in DELIVERY_CODE:
        return DELIVERY_CODE[oblast]
    if okrug in DELIVERY_CODE:
        return DELIVERY_CODE[okrug]
    return DELIVERY_CODE["DEFAULT"]
